import { AppBarProps } from '../AppBar';
import { AvatarProps } from '../Avatar';
import { BackdropProps } from '../Backdrop';
import { BadgeProps } from '../Badge';
import { BottomNavigationProps } from '../BottomNavigation';
import { BottomNavigationActionProps } from '../BottomNavigationAction';
import { BoxProps } from '../Box';
import { BreadcrumbsProps } from '../Breadcrumbs';
import { ButtonProps } from '../Button';
import { ButtonBaseProps } from '../ButtonBase';
import { ButtonGroupProps } from '../ButtonGroup';
import { CardProps } from '../Card';
import { CardActionAreaProps } from '../CardActionArea';
import { CardActionsProps } from '../CardActions';
import { CardContentProps } from '../CardContent';
import { CardHeaderProps } from '../CardHeader';
import { CardMediaProps } from '../CardMedia';
import { CheckboxProps } from '../Checkbox';
import { ChipProps } from '../Chip';
import { CircularProgressProps } from '../CircularProgress';
import { ClickAwayListenerProps } from '../ClickAwayListener';
import { CollapseProps } from '../Collapse';
import { ContainerProps } from '../Container';
import { CssBaselineProps } from '../CssBaseline';
import { DialogProps } from '../Dialog';
import { DialogActionsProps } from '../DialogActions';
import { DialogContentProps } from '../DialogContent';
import { DialogContentTextProps } from '../DialogContentText';
import { DialogTitleProps } from '../DialogTitle';
import { DividerProps } from '../Divider';
import { DrawerProps } from '../Drawer';
import { ExpansionPanelProps } from '../ExpansionPanel';
import { ExpansionPanelActionsProps } from '../ExpansionPanelActions';
import { ExpansionPanelDetailsProps } from '../ExpansionPanelDetails';
import { ExpansionPanelSummaryProps } from '../ExpansionPanelSummary';
import { FabProps } from '../Fab';
import { FadeProps } from '../Fade';
import { FilledInputProps } from '../FilledInput';
import { FormControlProps } from '../FormControl';
import { FormControlLabelProps } from '../FormControlLabel';
import { FormGroupProps } from '../FormGroup';
import { FormHelperTextProps } from '../FormHelperText';
import { FormLabelProps } from '../FormLabel';
import { GridProps } from '../Grid';
import { GridListProps } from '../GridList';
import { GridListTileProps } from '../GridListTile';
import { GridListTileBarProps } from '../GridListTileBar';
import { GrowProps } from '../Grow';
import { HiddenProps } from '../Hidden';
import { IconProps } from '../Icon';
import { IconButtonProps } from '../IconButton';
import { InputProps } from '../Input';
import { InputAdornmentProps } from '../InputAdornment';
import { InputBaseProps } from '../InputBase';
import { InputLabelProps } from '../InputLabel';
import { LinearProgressProps } from '../LinearProgress';
import { LinkProps } from '../Link';
import { ListProps } from '../List';
import { ListItemProps } from '../ListItem';
import { ListItemAvatarProps } from '../ListItemAvatar';
import { ListItemIconProps } from '../ListItemIcon';
import { ListItemSecondaryActionProps } from '../ListItemSecondaryAction';
import { ListItemTextProps } from '../ListItemText';
import { ListSubheaderProps } from '../ListSubheader';
import { MenuProps } from '../Menu';
import { MenuItemProps } from '../MenuItem';
import { MenuListProps } from '../MenuList';
import { MobileStepperProps } from '../MobileStepper';
import { ModalProps } from '../Modal';
import { NativeSelectProps } from '../NativeSelect';
import { NoSsrProps } from '../NoSsr';
import { OutlinedInputProps } from '../OutlinedInput';
import { PaperProps } from '../Paper';
import { PopoverProps } from '../Popover';
import { PopperProps } from '../Popper';
import { PortalProps } from '../Portal';
import { RadioProps } from '../Radio';
import { RadioGroupProps } from '../RadioGroup';
import { RootRefProps } from '../RootRef';
import { ScopedCssBaselineProps } from '../ScopedCssBaseline';
import { SelectProps } from '../Select';
import { SlideProps } from '../Slide';
import { SliderProps } from '../Slider';
import { SnackbarProps } from '../Snackbar';
import { SnackbarContentProps } from '../SnackbarContent';
import { StepProps } from '../Step';
import { StepButtonProps } from '../StepButton';
import { StepConnectorProps } from '../StepConnector';
import { StepContentProps } from '../StepContent';
import { StepIconProps } from '../StepIcon';
import { StepLabelProps } from '../StepLabel';
import { StepperProps } from '../Stepper';
import { SvgIconProps } from '../SvgIcon';
import { SwipeableDrawerProps } from '../SwipeableDrawer';
import { SwitchProps } from '../Switch';
import { TabProps } from '../Tab';
import { TableProps } from '../Table';
import { TableBodyProps } from '../TableBody';
import { TableCellProps } from '../TableCell';
import { TableContainerProps } from '../TableContainer';
import { TableFooterProps } from '../TableFooter';
import { TableHeadProps } from '../TableHead';
import { TablePaginationProps } from '../TablePagination';
import { TableRowProps } from '../TableRow';
import { TableSortLabelProps } from '../TableSortLabel';
import { TabsProps } from '../Tabs';
import { TextFieldProps } from '../TextField';
import { TextareaAutosizeProps } from '../TextareaAutosize';
import { ToolbarProps } from '../Toolbar';
import { TooltipProps } from '../Tooltip';
import { TypographyProps } from '../Typography';
import { ZoomProps } from '../Zoom';
import { OverridableComponent.d.tsProps } from '../OverridableComponent.d.ts';

export type ComponentsProps = {
	[Name in keyof ComponentPropsList]?: Partial<ComponentPropsList[Name]>
};
export interface ComponentsPropsList {
		VueUiAppBar: AppBarProps;
	VueUiAvatar: AvatarProps;
	VueUiBackdrop: BackdropProps;
	VueUiBadge: BadgeProps;
	VueUiBottomNavigation: BottomNavigationProps;
	VueUiBottomNavigationAction: BottomNavigationActionProps;
	VueUiBox: BoxProps;
	VueUiBreadcrumbs: BreadcrumbsProps;
	VueUiButton: ButtonProps;
	VueUiButtonBase: ButtonBaseProps;
	VueUiButtonGroup: ButtonGroupProps;
	VueUiCard: CardProps;
	VueUiCardActionArea: CardActionAreaProps;
	VueUiCardActions: CardActionsProps;
	VueUiCardContent: CardContentProps;
	VueUiCardHeader: CardHeaderProps;
	VueUiCardMedia: CardMediaProps;
	VueUiCheckbox: CheckboxProps;
	VueUiChip: ChipProps;
	VueUiCircularProgress: CircularProgressProps;
	VueUiClickAwayListener: ClickAwayListenerProps;
	VueUiCollapse: CollapseProps;
	VueUiContainer: ContainerProps;
	VueUiCssBaseline: CssBaselineProps;
	VueUiDialog: DialogProps;
	VueUiDialogActions: DialogActionsProps;
	VueUiDialogContent: DialogContentProps;
	VueUiDialogContentText: DialogContentTextProps;
	VueUiDialogTitle: DialogTitleProps;
	VueUiDivider: DividerProps;
	VueUiDrawer: DrawerProps;
	VueUiExpansionPanel: ExpansionPanelProps;
	VueUiExpansionPanelActions: ExpansionPanelActionsProps;
	VueUiExpansionPanelDetails: ExpansionPanelDetailsProps;
	VueUiExpansionPanelSummary: ExpansionPanelSummaryProps;
	VueUiFab: FabProps;
	VueUiFade: FadeProps;
	VueUiFilledInput: FilledInputProps;
	VueUiFormControl: FormControlProps;
	VueUiFormControlLabel: FormControlLabelProps;
	VueUiFormGroup: FormGroupProps;
	VueUiFormHelperText: FormHelperTextProps;
	VueUiFormLabel: FormLabelProps;
	VueUiGrid: GridProps;
	VueUiGridList: GridListProps;
	VueUiGridListTile: GridListTileProps;
	VueUiGridListTileBar: GridListTileBarProps;
	VueUiGrow: GrowProps;
	VueUiHidden: HiddenProps;
	VueUiIcon: IconProps;
	VueUiIconButton: IconButtonProps;
	VueUiInput: InputProps;
	VueUiInputAdornment: InputAdornmentProps;
	VueUiInputBase: InputBaseProps;
	VueUiInputLabel: InputLabelProps;
	VueUiLinearProgress: LinearProgressProps;
	VueUiLink: LinkProps;
	VueUiList: ListProps;
	VueUiListItem: ListItemProps;
	VueUiListItemAvatar: ListItemAvatarProps;
	VueUiListItemIcon: ListItemIconProps;
	VueUiListItemSecondaryAction: ListItemSecondaryActionProps;
	VueUiListItemText: ListItemTextProps;
	VueUiListSubheader: ListSubheaderProps;
	VueUiMenu: MenuProps;
	VueUiMenuItem: MenuItemProps;
	VueUiMenuList: MenuListProps;
	VueUiMobileStepper: MobileStepperProps;
	VueUiModal: ModalProps;
	VueUiNativeSelect: NativeSelectProps;
	VueUiNoSsr: NoSsrProps;
	VueUiOutlinedInput: OutlinedInputProps;
	VueUiPaper: PaperProps;
	VueUiPopover: PopoverProps;
	VueUiPopper: PopperProps;
	VueUiPortal: PortalProps;
	VueUiRadio: RadioProps;
	VueUiRadioGroup: RadioGroupProps;
	VueUiRootRef: RootRefProps;
	VueUiScopedCssBaseline: ScopedCssBaselineProps;
	VueUiSelect: SelectProps;
	VueUiSlide: SlideProps;
	VueUiSlider: SliderProps;
	VueUiSnackbar: SnackbarProps;
	VueUiSnackbarContent: SnackbarContentProps;
	VueUiStep: StepProps;
	VueUiStepButton: StepButtonProps;
	VueUiStepConnector: StepConnectorProps;
	VueUiStepContent: StepContentProps;
	VueUiStepIcon: StepIconProps;
	VueUiStepLabel: StepLabelProps;
	VueUiStepper: StepperProps;
	VueUiSvgIcon: SvgIconProps;
	VueUiSwipeableDrawer: SwipeableDrawerProps;
	VueUiSwitch: SwitchProps;
	VueUiTab: TabProps;
	VueUiTable: TableProps;
	VueUiTableBody: TableBodyProps;
	VueUiTableCell: TableCellProps;
	VueUiTableContainer: TableContainerProps;
	VueUiTableFooter: TableFooterProps;
	VueUiTableHead: TableHeadProps;
	VueUiTablePagination: TablePaginationProps;
	VueUiTableRow: TableRowProps;
	VueUiTableSortLabel: TableSortLabelProps;
	VueUiTabs: TabsProps;
	VueUiTextField: TextFieldProps;
	VueUiTextareaAutosize: TextareaAutosizeProps;
	VueUiToolbar: ToolbarProps;
	VueUiTooltip: TooltipProps;
	VueUiTypography: TypographyProps;
	VueUiZoom: ZoomProps;
	VueUiOverridableComponent.d.ts: OverridableComponent.d.tsProps;
}